### ISSUE TITLE
Launching Singstar results in stuck loading Screen

### ISSUE THREAD

**Issue by LoKoFe** [weathondev/SingstarCreatorTutorial#6]
So after fiddling around with all the steps i finally managed to create a Singstar1.iso and launching it over the Playstation. The problem i have is that it only shows the loading screen and doesnt do anything else. I let it sit for at least an hour, while testing.
I've got an unmodded Playstation 2 Slim Model. From what i read it should work on that.
The Songs i used from testing were all exported directly from Singstar discs, so there should be no problem with that i guess?
In Singstar Creator i used the .mp3 to create the .sca, the .avi for the .scv, and the jpg for the cover. I left the .txt files like they were. ([The Rolling Stones - Paint It, Black.txt](https://github.com/user-attachments/files/17118253/The.Rolling.Stones.-.Paint.It.Black.txt))

Did anybody else run into this problem? I read anywhere that it may have to do with how much songs you add, i tried at first with one, but also tried with ten songs. I also had problems with converting .mp4 files. It just wouldn't work. After switching to .avi files it at least created the .iso

**Comment by weathondev** [comment]
Hi! Please upload me somewhere an iso that doesn't work and the raw data which you used to create it so I can troubleshoot.

**Comment by LoKoFe** [comment]
Send you a Discord request a while ago.

**Comment by weathondev** [comment]
Didn't see it and can't see it now either, or do you have a different name there?

**Comment by LoKoFe** [comment]
Hmm... cant send you a new one. Can you try sending me one?
Name: lokofe
old: LoKoFe#8018

**Comment by weathondev** [comment]
We were able to solve the issue via discord :)
Actually there were two issues
1) the pademu settings on OPL were not correct, probably copied the files from the github but they were later overwritten or defaulted by accident/some other action
2) Additionally we tried burning LoKoFes iso to DVDs but they wouldn't load while mine would. Turns out you have to start Singstar Creator as an admin, otherwise the ESL patching will silently not be done. Added it to the readme.
